
import Navbar from "@/components/Navbar";
import "@/style/globals.css";
import Search from "@/components/Search";


/* import {
  Space_Mono,
  PT_Serif,
  Open_Sans,
  Pixelify_Sans,
} from "next/font/google";



const mono = Space_Mono({variable: "--font-mono", weight: ["400", "700"], subsets: ["latin"] });
const serif = PT_Serif({ weight: ["400", "700"], subsets: ["latin"] });
const sans = Open_Sans({ weight: ["400", "700"], subsets: ["latin"] });
const pixel = Pixelify_Sans({ weight: ["400", "700"], subsets: ["latin"] }); */

export const metadata = {
  title: "Dictionary web app",
  description: "Generated by create next app and tailwind",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" >
      <body  >
      <header>
        <Navbar />
        <Search />
      </header>
        
        {children}
        </body>
    </html>
  );
}
